[2주차] TodoList 리팩토링 + 번들링
DKU-STUDY/js-study-lv1 pull request #19
Opened 2021-07-06 06:37 UTC by inust33

- 우선 에러가 나는데 원인을 찾기가 힘들어 PR먼저 해놓았습니다.

- step1 폴더에  services.js에 render 및 각종 additem 등의 기능등을 리팩토링하고 render만 export한 상태에서 브라우저에 로드시 
cannot read property of addeventlistener Null이라는 에러가 뜹니다.  services.js 파일에서 뜨는 것으로 나옵니다.

- script 태그의 문제 혹은 addeventListner 함수의 대상이 null이라 발생하는 문제라는 구글링 결과에 태그 등록 위치를 이러저러하게 옮겨 보았지만 소용이 없었습니다. 

- 번들러는 parcel을 선택해보았습니다. 별다른 환경설정이 필요없고 ES6 문법을 지원한다는 점이 흥미가 갔습니다.
- 번들러 및 모듈의 역사에 대해서 공부할 수 있어서  유익한 시간이었습니다.
- 또한 자바스크립트가 얼마나 짧은 시간 안에 프론트엔드 언어로써 급격히 성장했는지 체감할 수 있었습니다. 
- 클래스 추상화나 import export의 개념을 더 확실히 공부해서 에러없이 번들링 및 브라우저 로딩을 하고싶다는 생각이 들었습니다.

2021-07-07 13:35 UTC, JunilHwang commented
지금 confict가 발생하고 있네요. 일단 충돌 나는 부분 해결 부탁드려요!

2021-07-07 13:41 UTC, JunilHwang requested changes
안녕하세요 인우님! 요즘 이것 저것 많이 하시는 것 같아요 ㅋㅋ 알찬 방학을 보내고 계신 것 같네요 ㅎㅎ

리팩토링 진행하신다고 하셔서 일단 이정도 까지만 리뷰 남기겠습니다!

2021-07-07 13:41 UTC, JunilHwang commented on step1/src/services.js
> +}
조금 더 가독성을 신경쓰면서 포맷을 지켜보면 어떨까요?
가령

```js
    $complete.forEach(
      ($el) => $el.addEventListener("click", toggleItem)
    );
```
이런 형태로 표현하면 더 보기 좋지 않나요 ㅎㅎ?

2021-07-07 13:41 UTC, JunilHwang commented on step1/src/src/services.js
> +}
개행이 필욯란 부분에는 개행을 해주세요!

2021-07-07 13:41 UTC, JunilHwang commented on step1/src/src/services.js
> +            .addEventListener('keydown', (event) => { if (event.code === 'Escape') { state.selectedItem = -1; render(); } });
```suggestion
        $modifierForm.addEventListener('keydown', ({ code }) => {
          if (code !== 'Escape') return;
          state.selectedItem = -1;
          render();
        });
```
이렇게 표현해주면 어떨까요?

2021-07-07 13:41 UTC, JunilHwang commented on step1/src/src/services.js
> +            addEventListener('reset', resetItem);
```suggestion
        $modifierForm.addEventListener('submit', updateItem);
        $modifierForm.addEventListener('reset', resetItem);
```
`한 줄에 점 하나` 이기 때문에 이렇게 표현하는게 더 자연스럽답니다!

2021-07-07 13:41 UTC, JunilHwang commented on step1/src/src/services.js
> +            addEventListener('reset', resetItem);
다른 코드도 이런 형태로 수정해주세요~

2021-07-09 22:26 UTC, inust33 commented
> 지금 confict가 발생하고 있네요. 일단 충돌 나는 부분 해결 부탁드려요!

conflict는 해결했습니다!

2021-07-10 08:21 UTC, JunilHwang requested changes
안녕하세요 인우님! 리팩토링 진행 잘 해주셨는데, 문제가 실행이 되지 않는 코드네요 ㅎㅎ
제가 작성한 Component를 사용하는것도 좋지만, 인우님이 해해서 인우님 많의 코드로 다시 만들어 보는걸 권유드려요!
일단 실행할 수 있는 형태로 만드는게 제일 중요해보이네요.

그리고 2주차 미션 코드인데 step1에다가 작성해주신 것 같아요!
기존의 step1은 유지해주시고, step2에다가 별도로 리팩토링 코드 작성해서 올려주시면 더 좋을 것 같아요~

2021-07-10 08:21 UTC, JunilHwang commented on .gitignore
> +dist/
git ignore의 경우
```bash
$ git rm -r --cached .
$ git add .
``` 
이렇게 캐시를 한 번 지워주고 다시 추가해줘야 반영된답니다!

2021-07-10 08:21 UTC, JunilHwang commented on step1/src/app.js
> +    }
```suggestion
    template() {
        return `
          <h1>📃 TodoList</h1>
          <form data-component="appenderForm" action="" method="post"></form>
          <ul data-component="modifierForm items"></ul>
        `;
    }
```
이렇게 indent를 한 칸 늘려주세요!

2021-07-10 08:21 UTC, JunilHwang commented on step1/index.html
> +    <script src="./src/main.js" defer></script>
지금 main.js에 아무 것도 없어서 실행이 제대로 안되고 있네요!

2021-07-10 08:21 UTC, JunilHwang commented on step1/src/app.js
> +
전체적으로 오류가 많은 코드네요 ㅠㅠ 한 번 직접 실행해서 확인해보실 수 있을까요?

2021-07-10 08:21 UTC, JunilHwang commented on step1/src/app.js
> +        selectedItem = id;
`const`로 선언할 경우 재할당이 불가능합니다. 따라서 `this.$state.selectedItem = id` 처럼 작성해주셔야 해요!

2021-07-10 08:21 UTC, JunilHwang commented on step1/src/app.js
> +        this.setState({ selectedItem });
```suggestion
        this.setState({ selectedItem: id });
```
이렇게만 해도 되겠네요

2021-07-10 11:10 UTC, JunilHwang requested changes
현재 발생하는 오류들에 대해 다시 리뷰 남겼습니다. 한 번 확인해주세요!

2021-07-10 11:10 UTC, JunilHwang commented on step1/src/app.js
> +        }
이 부분도 const에서 재할당 하고 있네요.

2021-07-10 11:10 UTC, JunilHwang commented on step1/src/core/Component.js
> +    }
Component에는 mounnted로 선언되어있네요. 그래서 태그들이 정상적으로 마운트되지 않고 있답니다.
이름을 mounted로 바꾸거나 Component를 상속한 class에서 mounted 대신에 mounnted로 변경해주세요.

2021-07-10 11:10 UTC, JunilHwang commented on step1/src/core/Component.js
> +    }
그 다음에 발생하는 오류까지 같이 처리해주세요.

2021-07-11 12:13 UTC, JunilHwang reviewed
안녕하세요 인우님! 지금도 여전히 다양한 오류가 있네요 ㅎㅎ 시간 있을 때 하나씩 고쳐보세요! 일단 지금까지 작성한 부분은 merge 해놓겠습니다.

2021-07-11 12:13 UTC, merged

2021-07-11 16:53 UTC, inust33 commented
> 안녕하세요 인우님! 지금도 여전히 다양한 오류가 있네요 ㅎㅎ 시간 있을 때 하나씩 고쳐보세요! 일단 지금까지 작성한 부분은 merge 해놓겠습니다.

오류를 최대한 수정하였으나 submit이벤트에서 input의 value를 읽어오지 못하고 모두 undefined로 표시하는 오류가 있습니다.  메소드에 문제가 있나 싶어서 추상화한 메소드 말고 addEventListener로도 해봤는데 해결되지 않았습니다. form과 submit의 작동방식에서 뭔가 잘못이 있는건지... 궁금합니다. 봐주실 수 있을까요?

2021-07-11 17:28 UTC, JunilHwang commented
힌트를 드리자면, app.js에 작성한 addItem이 문제입니다. 변수명을 잘 살펴보세요.
그리고 const로 선언한 변수에 재 할당하는 부분은 전부 제거해주세요. 몇 번 말했는데 계속 잔여 코드가 있네요 ㅠㅠ